### ISSUE TITLE
get "RuntimeError: Unexpected error in an Op's C code." when using GPU

### ISSUE THREAD

**Issue by ganji15** [mcf06/theano_ctc#12]
Hi, I get "RuntimeError: Unexpected error in an Op's C code." when I run "tests/test_ctc.py" by using [GPU](#GPU). However,  no error occurs when I run the test example by using CPU. Would you please help me to solve this problem?  Thank you very much!

P.S.  My envirment is "Ubuntu14.04 + GTX1070 + theano_ctc"

Error details when using GPU:
▶ python test_ctc.py 
Using gpu device 0: GeForce GTX 1070 (CNMeM is disabled, cuDNN 5005)
Activations
[[[  0.   0.   0.   0.   0.]
  [  1.   2.   3.   4.   5.]
  [ -5.  -4.  -3.  -2.  -1.]]

 [[  0.   0.   0.   0.   0.]
  [  6.   7.   8.   9.  10.]
  [-10.  -9.  -8.  -7.  -6.]]

 [[  0.   0.   0.   0.   0.]
  [ 11.  12.  13.  14.  15.]
  [-15. -14. -13. -12. -11.]]]

Softmax outputs
[[[ 0.2         0.2         0.2         0.2         0.2       ]
  [ 0.01165623  0.03168492  0.08612854  0.23412167  0.63640863]
  [ 0.01165623  0.03168492  0.08612854  0.23412167  0.63640863]]

 [[ 0.2         0.2         0.2         0.2         0.2       ]
  [ 0.01165623  0.03168492  0.08612854  0.23412167  0.63640863]
  [ 0.01165623  0.03168492  0.08612854  0.23412167  0.63640863]]

 [[ 0.2         0.2         0.2         0.2         0.2       ]
  [ 0.01165623  0.03168492  0.08612854  0.23412167  0.63640863]
  [ 0.01165623  0.03168492  0.08612854  0.23412167  0.63640863]]]

Theano function to calculate costs and gradient of mean(costs):
<theano_ctc.gpu_ctc.GpuCtc object at 0x7f22b5848710>.0 [id A] 'ctc_cost'   0
 |acts [id B]
 |actT [id C]
 |labels [id D]
HostFromGpu [id E] '(dmean/dacts)'   9
 |GpuElemwise{Mul}[(0, 1)] [id F] ''   8
   |GpuReshape{3} [id G] ''   7
   | |GpuAlloc [id H] ''   6
   | | |GpuElemwise{Inv}[(0, 0)] [id I] ''   5
   | | | |GpuFromHost [id J] ''   4
   | | |   |Elemwise{Cast{float32}} [id K] ''   3
   | | |     |InplaceDimShuffle{x} [id L] ''   2
   | | |       |Shape_i{0} [id M] ''   1
   | | |         |<theano_ctc.gpu_ctc.GpuCtc object at 0x7f22b5848710>.0 [id A] 'ctc_cost'   0
   | | |Shape_i{0} [id M] ''   1
   | |TensorConstant{[ 1 -1  1]} [id N]
   |<theano_ctc.gpu_ctc.GpuCtc object at 0x7f22b5848710>.1 [id A] 'ctc_grad'   0

Theano function to calculate costs:
<theano_ctc.gpu_ctc.GpuCtc object at 0x7f22b4b6cc10> [id A] 'ctc_cost'   0
 |acts [id B]
 |actT [id C]
 |labels [id D] 

warpctc.compute_ctc_loss() exited with status 3
Traceback (most recent call last):
  File "test_ctc.py", line 62, in <module>
    cost, grad = train()
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in **call**
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in **call**
    outputs = self.fn()
RuntimeError: Unexpected error in an Op's C code. No Python exception was set.
Apply node that caused the error: <theano_ctc.gpu_ctc.GpuCtc object at 0x7f22b5848710>(acts, actT, labels)
Toposort index: 0
Inputs types: [CudaNdarrayType(float32, 3D), TensorType(int32, vector), TensorType(int32, matrix)]
Inputs shapes: [(3, 3, 5), (3,), (3, 2)]
Inputs strides: [(15, 5, 1), (4,), (8, 4)]
Inputs values: ['not shown', array([1, 3, 3], dtype=int32), 'not shown']
Outputs clients: [[Shape_i{0}(ctc_cost), 'output'], [GpuElemwise{Mul}[(0, 1)](GpuReshape{3}.0, ctc_grad)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "test_ctc.py", line 45, in <module>
    tCost = ctc_cost(tsActs, tsLabels, tsActT)
  File "/usr/local/lib/python2.7/dist-packages/theano_ctc/**init**.py", line 40, in ctc_cost
    return GpuCtc()(acts, labels, input_lengths)
  File "/usr/local/lib/python2.7/dist-packages/theano_ctc/gpu_ctc.py", line 17, in **init**
    self.costs = T.fvector(name="ctc_cost")

Debugprint of the apply node: 
<theano_ctc.gpu_ctc.GpuCtc object at 0x7f22b5848710>.0 [id A] <TensorType(float32, vector)> 'ctc_cost'  
<theano_ctc.gpu_ctc.GpuCtc object at 0x7f22b5848710>.1 [id A] <CudaNdarrayType(float32, 3D)> 'ctc_grad'   

Storage map footprint:
- acts, Shared Input, Shape: (3, 3, 5), ElemSize: 4 Byte(s), TotalSize: 180 Byte(s)
- labels, Shared Input, Shape: (3, 2), ElemSize: 4 Byte(s), TotalSize: 24 Byte(s)
- TensorConstant{[ 1 -1  1]}, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
- actT, Shared Input, Shape: (3,), ElemSize: 4 Byte(s), TotalSize: 12 Byte(s)
  TotalSize: 240 Byte(s) 0.000 GB
  TotalSize inputs: 240 Byte(s) 0.000 GB

**Comment by ganji15** [comment]
I just find that my warp-ctc is not correctly builded, thus causing the error "warpctc.compute_ctc_loss() exited with status 3" occurs.  I compile warp-ctc correctly and solve the problem.

code in https://github.com/ganji15/warp-ctc/blob/master/src/ctc_entrypoint.cpp
"""
 else if (info.loc == CTC_GPU) {
#ifdef **CUDACC**
        GpuCTC<float> ctc(alphabet_size, minibatch, workspace, info.stream);

```
    if (gradients != NULL)
        return ctc.cost_and_grad(activations, gradients, costs,
                                 flat_labels, label_lengths,
                                 input_lengths);
    else
        return ctc.score_forward(activations, costs, flat_labels,
                                 label_lengths, input_lengths);
```

#else
        std::cerr << "GPU execution requested, but not compiled with GPU support" << std::endl;
        return CTC_STATUS_EXECUTION_FAILED;
#endif
"""
